# Generated by Django 2.2.5 on 2019-09-28 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='menssagem',
            new_name='mensagem',
        ),
    ]
