# Generated by Django 2.2.5 on 2019-09-29 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190927_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cidade',
            field=models.CharField(default='Santa Maria', max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.CharField(default='RS', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nascimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pais',
            field=models.CharField(default='BR', max_length=50, verbose_name='País'),
        ),
    ]
