# Generated by Django 2.2.5 on 2019-09-28 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190927_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nascimento',
            field=models.DateField(default=datetime.datetime(2019, 9, 27, 23, 38, 20, 910541), verbose_name='Data de Nascimento'),
        ),
    ]
