# Generated by Django 2.2.5 on 2019-09-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190928_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genero',
            field=models.CharField(default='macho', max_length=6, verbose_name='Genero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(default='343434', max_length=15, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
