# Generated by Django 2.2.5 on 2019-09-28 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190928_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='genero',
            field=models.CharField(default='male', max_length=6, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(default='234325', max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Cidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Estado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Pais'),
        ),
    ]
