# Generated by Django 2.2.5 on 2019-09-28 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190928_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Cidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Estado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Pais'),
        ),
    ]
